= CalConnect Standard: Collection Query Report for Web Distributed Authoring and Versioning (WebDAV)

This work item belongs to CalConnect CALENDAR TC.

image:https://github.com/CalConnect/cc-collection-query/workflows/generate/badge.svg["Build Status", link="https://github.com/CalConnect/cc-collection-query/actions?workflow=generate"]

This document is available in its rendered forms here:

* https://calconnect.github.io/cc-collection-query/[Collection Query Report for Web Distributed Authoring and Versioning (WebDAV) (HTML)]

== General

This document specifies the 

The document is published as the following:

* CalConnect CC 51020
* IETF draft-murchison-webdav-collection-query


== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/cc-collection-query/
----


== Installing build tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate --agree-to-terms
----


== Building the document

[source,sh]
----
metanorma site generate --agree-to-terms
----

The generated documents are accessible under `_site/`.


== Iterating the document

[source,sh]
----
metanorma site generate --agree-to-terms
open _site/index.html
----


== License

Copyright its respective authors and CalConnect.
