== Conventions Used in This Document

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD",
"SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this
document are to be interpreted as described in BCP 14 <<RFC2119>> <<RFC8174>>
when, and only when, they appear in all capitals, as shown here.

This document uses XML DTD fragments (<<W3C.REC-xml-20081126>>, Section 3.2) as
a purely notational convention. WebDAV request and response bodies cannot be
validated by a DTD due to the specific extensibility rules defined in
<<RFC4918,section=17>> and due to the fact that all XML elements defined by this
specification use the XML namespace name "DAV:".

In particular:

* Element names use the "DAV:" namespace.
* Element ordering is irrelevant unless explicitly stated otherwise.
* Extension elements (elements not already defined as valid child elements) may be
added anywhere, except when explicitly stated otherwise.
* Extension attributes (attributes not already defined as valid for this element) may
be added anywhere, except when explicitly stated otherwise.

When an XML element type in the "DAV:" namespace is referenced in this document
outside of the context of an XML fragment, the string "DAV:" will be prefixed to
the element type.

This document inherits, and sometimes extends, DTD productions from
<<RFC4918,section=14>>.
